#define DESK_CONTROL_MOVE_UP    HYPR(KC_U)
#define DESK_CONTROL_MOVE_DOWN  HYPR(KC_E)
#define DESK_CONTROL_STOP       KC_NO
#define DESK_CONTROL_STAND      HYPR(KC_K)
#define DESK_CONTROL_SIT        HYPR(KC_J)
#define DESK_CONTROL_FAV        HYPR(KC_M)
#define DESK_CONTROL_TOGGLE     HYPR(KC_BSPC)

#define DC_TOGGL                DESK_CONTROL_TOGGLE
