// full name versions of the magnet shortcuts
#define MAGNET_FULLSCREEN               LCA(KC_ENTER)
#define MAGNET_LEFT_HALF                LCA(KC_LEFT)
#define MAGNET_RIGHT_HALF               LCA(KC_RIGHT)
#define MAGNET_UPPER_HALF               LCA(KC_UP)
#define MAGNET_BOTTOM_HALF              LCA(KC_DOWN)

#define MAGNET_LEFT_THIRD               LCA(KC_D)
#define MAGNET_MIDDLE_THIRD             LCA(KC_F)
#define MAGNET_RIGHT_THIRD              LCA(KC_G)

#define MAGNET_UPPER_LEFT_QUADRANT      LCA(KC_U)
#define MAGNET_UPPER_RIGHT_QUADRANT     LCA(KC_I)
#define MAGNET_BOTTOM_LEFT_QUADRANT     LCA(KC_J)
#define MAGNET_BOTTOM_RIGHT_QUADRANT    LCA(KC_K)

#define MAGNET_LEFT_TWO_THIRDS          LCA(KC_E)
#define MAGNET_RIGHT_TWO_THIRDS         LCA(KC_T)

// short names of all above shortcuts
#define MG_FSCR     MAGNET_FULLSCREEN

#define MG_LF_HF    MAGNET_LEFT_HALF
#define MG_RT_HF    MAGNET_RIGHT_HALF
#define MG_UP_HF    MAGNET_UPPER_HALF
#define MG_BT_HF    MAGNET_BOTTOM_HALF

#define MG_LF_TD    MAGNET_LEFT_THIRD
#define MG_MD_TD    MAGNET_MIDDLE_THIRD
#define MG_RT_TD    MAGNET_RIGHT_THIRD

#define MG_UL_QD    MAGNET_UPPER_LEFT_QUADRANT
#define MG_UR_QD    MAGNET_UPPER_RIGHT_QUADRANT
#define MG_BL_QD    MAGNET_BOTTOM_LEFT_QUADRANT
#define MG_BR_QD    MAGNET_BOTTOM_RIGHT_QUADRANT

#define MG_L2_TD    MAGNET_LEFT_TWO_THIRDS
#define MG_R2_TD    MAGNET_RIGHT_TWO_THIRDS
